### ISSUE TITLE
mockRequest results in TypeError: Cannot read property ‘apply’ of undefined

### ISSUE THREAD

**Issue by serzhshakur** [codeceptjs/CodeceptJS#2700]
#### What are you trying to achieve?
I’m trying to write a test with `mockRequest` involved. I just set up a [small project](https://github.com/serzhshakur/codeceptjs-example) and wrote a basic test like follows:

```
Feature('Search');

const response = [{"phrase": "test"}, {"phrase": "hello"}, {"phrase": "world"}, {"phrase": "duckduckgo"}];

Scenario('search in Duckduckgo', ({I}) => {
    I.amOnPage('https://duckduckgo.com/');
    I.mockRequest('GET', 'https://duckduckgo.com/ac/*', response);
    I.fillField('#search_form_input_homepage', 'hello');
});
```

#### What do you get instead?

when I run `yarn codeceptjs run --steps --debug --verbose` I’m getting the following:

```bash
❯ yarn codeceptjs run --steps --debug --verbose
CodeceptJS v3.0.2
Using test root "/home/sergey/dev/codecept-example"
Helpers: Puppeteer, MockRequestHelper
Plugins: screenshotOnFail, retryFailedStep, tryTo

Search --
    [1]  Starting recording promises
  search in Duckduckgo
    I am on page "https://duckduckgo.com/"
    › [Url] https://duckduckgo.com/
    I mock request "GET", "https://duckduckgo.com/ac/*", [{"phrase":"test"},{"phrase":"hello"},{"phras…
    [1] Retrying... Attempt #2
    [1] Retrying... Attempt #3
    [1] Retrying... Attempt #4
    [1] Retrying... Attempt #5
    [1] Retrying... Attempt #6
    [1] Error | TypeError: Cannot read property 'apply' of undefined
    [1] Error | TypeError: Cannot read property 'apply' of undefined
    [1] Error | TypeError: Cannot read property 'apply' of undefined
    [1] Starting <teardown> session
    [1] <teardown> Stopping recording promises
 › <screenshotOnFail> Test failed, try to save a screenshot
 › Screenshot is saving to /home/sergey/dev/codecept-example/output/search_in_Duckduckgo.failed.png
  ✖ FAILED in 5857ms

    [2]  Starting recording promises
    Polly was not disconnected, Puppeteer is already closed

-- FAILURES:

  1) Search
       search in Duckduckgo:
     Cannot read property 'apply' of undefined

      at PuppeteerCodeceptJSAdapter._callListenersWith (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/adapter-puppeteer/dist/cjs/pollyjs-adapter-puppeteer.js:2418:28)
      at PuppeteerCodeceptJSAdapter.attachToPageEvents (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/adapter-puppeteer/dist/cjs/pollyjs-adapter-puppeteer.js:2328:10)
      at PuppeteerCodeceptJSAdapter.onConnect (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/adapter-puppeteer/dist/cjs/pollyjs-adapter-puppeteer.js:2233:10)
      at PuppeteerCodeceptJSAdapter.connect (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/adapter/dist/cjs/pollyjs-adapter.js:1130:12)
      at Polly.connectTo (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6430:13)
      at /home/sergey/dev/codecept-example/node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6315:50
      at Array.forEach (<anonymous>)
      at Polly.configure (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6315:26)
      at new Polly (node_modules/@codeceptjs/mock-request/node_modules/@pollyjs/core/dist/cjs/pollyjs-core.js:6216:10)
      at PuppeteerConnector.connect (node_modules/@codeceptjs/mock-request/connector/Puppeteer.js:43:18)

```

### Details
* NodeJS Version: 15.2.1
* Operating System: Arch Linux

* My `package.json`:
```
{
  "name": "codecept-example",
  "version": "1.0.0",
  "description": "A test automation project using CodeceptJS",
  "main": "index.js",
  "scripts": {
    "test": "yarn codeceptjs run --steps",
    "debug": "yarn codeceptjs run --debug --verbose"
  },
  "license": "ISC",
  "dependencies": {
    "codeceptjs": "^3.0.2",
    "puppeteer": "^5.5.0"
  },
  "devDependencies": {
    "@codeceptjs/mock-request": "^0.3.0",
    "@pollyjs/adapter-puppeteer": "^5.0.0",
    "@pollyjs/core": "^5.0.0"
  }
}
```

* Configuration file:

```js
const { setHeadlessWhen } = require('@codeceptjs/configure');

setHeadlessWhen(process.env.HEADLESS);

exports.config = {
  tests: './tests/*_test.js',
  output: './output',
  helpers: {
    Puppeteer: {
      show: true,
      windowSize: '1200x900'
    },
    MockRequestHelper: {
      require: '@codeceptjs/mock-request',
    }
  },
  include: {
    I: './steps_file.js'
  },
  bootstrap: null,
  mocha: {},
  name: 'codecept-example',
  plugins: {
    pauseOnFail: {},
    retryFailedStep: {
      enabled: true
    },
    tryTo: {
      enabled: true
    },
    screenshotOnFail: {
      enabled: true
    }
  }
}

```

**Comment by serzhshakur** [comment]
It turned out this is caused by the problem at pollyjs side https://github.com/Netflix/pollyjs/issues/345

**Comment by IanHong66** [comment]
I got the same problem while using mockRequest with Puppeteer. Same package dependency:

  "devDependencies": {
    "@codeceptjs/mock-request": "^0.3.0",
    "@pollyjs/adapter-puppeteer": "^5.0.0",
    "@pollyjs/core": "^5.0.0",
    "puppeteer": "^5.5.0",
  }

Hope this can be resolved soon.

**Comment by serzhshakur** [comment]
https://github.com/Netflix/pollyjs/issues/345 is now resolved and a new version 5.1.0 was released. 
Though mock-request has quite oldish deps. In order to override nested deps you can use `resolutions` in you package.json file (like I did [here](https://github.com/serzhshakur/codeceptjs-example/commit/7cb0806ed304914399752a70f8a63a31fbb9714b)).
@DavertMik consider upgrading packages list in mock-request

**Comment by IanHong66** [comment]
@serzhshakur I upgraded to pollyjs v5.1.0 but still gets the same error when mocking:

"devDependencies": {
"@codeceptjs/mock-request": "^0.3.0",
"@pollyjs/adapter-puppeteer": "^5.1.0",
"@pollyjs/core": "^5.1.0",
"puppeteer": "^5.5.0",
}

**Comment by serzhshakur** [comment]
@IanHong66 you have to also override pollyjs version that comes from mock-request's `package.json`. As I already mentioned in order to override nested deps I used yarn's [selective dependency resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) mechanism in my package.json. For npm I believe you can use something like [this](https://github.com/rogeriochaves/npm-force-resolutions)

**Comment by IanHong66** [comment]
@serzhshakur thank you for pointing this out again. I got what you mean now. I used npm-force-resolution and replicated what you did. Now the error is gone. But pollyjs seems not starting in browser either. When I do >npm ls, it says the version is invalid, is this normal?

```PS C:\Users\ian.hong\automation\UIAutomation\UIAutomationSuite> npm ls @pollyjs/core
UIAutomationSuite@1.0.0 C:\Users\ian.hong\automation\UIAutomation\UIAutomationSuite
`-- @codeceptjs/mock-request@0.3.0
  **`-- @pollyjs/core@5.1.0  invalid**

npm ERR! invalid: @pollyjs/core@5.1.0 C:\Users\ian.hong\automation\UIAutomation\UIAutomationSuite\node_modules\@codeceptjs\mock-request\node_modules\@pollyjs\core
PS C:\Users\ian.hong\automation\UIAutomation\UIAutomationSuite>  npm ls @pollyjs/adapter-puppeteer
UIAutomationSuite@1.0.0 C:\Users\ian.hong\automation\UIAutomation\UIAutomationSuite
`-- @codeceptjs/mock-request@0.3.0
  **`-- @pollyjs/adapter-puppeteer@5.1.0  invalid**

my config file is as below now:
```
  "resolutions": {
    "@pollyjs/adapter-puppeteer": "^5.1.0",
    "@pollyjs/core": "^5.1.0"
  },
  "devDependencies": {
    "@codeceptjs/mock-request": "^0.3.0",
    "npm-force-resolutions": "0.0.3",
    "puppeteer": "^5.5.0",
  },
```
![image](https://user-images.githubusercontent.com/29475644/102452715-eff0c700-408e-11eb-9ded-f75841b6dfb2.png)
